<?php require 'db.php'; $d=body();
foreach(['first_name','last_name','student_id','username','email','contact_number','password','section_id'] as $f) if(!isset($d[$f])||trim((string)$d[$f])===''){http_response_code(400);echo json_encode(['success'=>false,'message'=>ucwords(str_replace('_',' ',$f)).' is required.']);exit;}
if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL)){http_response_code(400);echo json_encode(['success'=>false,'message'=>'Invalid email address.']);exit;}
if(strlen($d['password'])<6){http_response_code(400);echo json_encode(['success'=>false,'message'=>'Password must be at least 6 characters.']);exit;}
try{$c=$pdo->prepare("SELECT username,email,student_id FROM users WHERE lower(username)=lower(:u) OR lower(email)=lower(:e) OR student_id=:s LIMIT 1");$c->execute([':u'=>trim($d['username']),':e'=>trim($d['email']),':s'=>trim($d['student_id'])]);$x=$c->fetch(PDO::FETCH_ASSOC);
if($x){$m=strcasecmp($x['username'],trim($d['username']))===0?'Username already exists.':(strcasecmp($x['email'],trim($d['email']))===0?'Email address already exists.':'Student ID already exists.');http_response_code(409);echo json_encode(['success'=>false,'message'=>$m]);exit;}
$st=$pdo->prepare("INSERT INTO users(first_name,last_name,student_id,username,email,contact_number,password_hash,section_id,role) VALUES(:a,:b,:c,:d,:e,:f,:g,:h,'student') RETURNING id");$st->execute([':a'=>trim($d['first_name']),':b'=>trim($d['last_name']),':c'=>trim($d['student_id']),':d'=>trim($d['username']),':e'=>trim($d['email']),':f'=>trim($d['contact_number']),':g'=>password_hash($d['password'],PASSWORD_DEFAULT),':h'=>(int)$d['section_id']]);$id=$st->fetchColumn();
$u=$pdo->prepare("SELECT u.id,u.first_name,u.last_name,u.student_id,u.username,u.email,u.contact_number,u.role,s.name section_name,d.code program FROM users u JOIN sections s ON s.id=u.section_id JOIN departments d ON d.id=s.department_id WHERE u.id=:i");$u->execute([':i'=>$id]);echo json_encode(['success'=>true,'message'=>'Registration successful.','user'=>$u->fetch(PDO::FETCH_ASSOC)]);
}catch(PDOException $e){http_response_code(500);echo json_encode(['success'=>false,'message'=>'Registration failed.']);}
?>
